### ISSUE TITLE
Missing osx-arm builds

### ISSUE THREAD

**Issue by jchodera** [conda-forge/pymbar-feedstock#20]
### Comment:

I notice the `osx-arm` versions are missing for `pymbar` on conda-forge:
https://anaconda.org/conda-forge/pymbar/files

Is it possible to build the `osx-arm` packages for the current `pymbar` release? Or do we need to change the [way we build the C extensions](https://github.com/choderalab/pymbar/blob/master/setup.py#L88-L92) to enable that?

cc @mikemhenry @ijpulidos

**Comment by mikemhenry** [comment]
I'll look into it! We might just need to re-render the feedstock to get those built

**Comment by jaimergp** [comment]
Put a PR like this for pymbar: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2640/files

**Comment by jchodera** [comment]
Thanks!

@mikemhenry @ijpulidos can one of you tackle this?

**Comment by mikemhenry** [comment]
Yes!

**Comment by jchodera** [comment]
@jaimergp: It doesn't look like @mikemhenry got to this, so I've created the PR here:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2719
