### ISSUE TITLE
Python 3.11 package missing for 3.1 LTS

### ISSUE THREAD

**Issue by orbeckst** [conda-forge/pymbar-feedstock#26]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There's currently no pymbar 3.1 LTS cf package for Python 3.11 available.

Would you be able to create one @mikemhenry ?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by mikemhenry** [comment]
It will take a bit of time to land on the CDN but this is now resolved, thanks @orbeckst for brining this to our attention!

**Comment by orbeckst** [comment]
Thank you, _much_ appreciated!

**Comment by orbeckst** [comment]
Packages are available and everything works on my end. Thanks again for the quick response.
